### ISSUE TITLE
All clients crash if an invalid color is used

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#10]
When using an invalid color (so basicly everything else between brackets, like this) will cause all clients connected to crash. In some cases the pc of someone I know even had to be restarted.

**Comment by alecxvs** [comment]
I need to figure out where this is actually happening. I don't recall if the text filters are in UTChat or UText itself, or if it's a bug with the color filter or the filter loader code.

**Comment by misterff1** [comment]
Color constants in chathandlers might have a check for it too actually. I removed it to stop the possibility of crashing and I recall that the text was split up and checked in there
