### ISSUE TITLE
Only chat:send and chat:print use UTChat

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#11]
The chat.broadcast and player.sendmessage function do not work on UTChat, but in the default. I have a workaround for this where I only use a file in the autorun folder instead of an integration file in every script.

**Comment by alecxvs** [comment]
I meant to try and get ahold of you on steam for this. I see where player send message wouldn't work but the rest should all be working, assuming the integrator is installed. I need to set up some tests anyway.

**Comment by misterff1** [comment]
I've been trying to contact you about this on steam. The issue is still there and when looking at the code, I see nothing that could create this bug
