### ISSUE TITLE
After using F3 a few times, the chat locks

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#12]
Somehow after a few times of using F3, the chat will not receive any messages anymore when typed while it is turned on again. Might be a JCMP issue on itself though

**Comment by alecxvs** [comment]
I need to look at the code again, but I believe the text input part is still entirely JCMP. Unless UTChat is enabling and disabling the text input itself, this would be a JCMP issue.

**Comment by misterff1** [comment]
Yeah I looked at it and I think it is entirely JCMP itself too. But no harm in checking eh? :)

**Comment by alecxvs** [comment]
This is actually a bug in UTChat, and mostly the cause to the fade errors. It occurs due to me sloppily handling the F3 key directly, but as of the latest version I can fix that.
