### ISSUE TITLE
Integrator is still broken, breaks chat entirely now.

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#22]
I am getting a bunch of errors when I install the latest version of UTChat:

error when running event PrintChat: 
utchat.lua on line 127: attempt to compare nil with number

The whole chat just won't work now because of this, so I am reverting to my autorun integrator until this is fixed.

**Comment by alecxvs** [comment]
That's pretty strange. Can you paste the full error?

**Comment by misterff1** [comment]
Yeah let me reproduce it. I am adding some more issues btw. some things are not fixed properly
(if you come online on steam, you can see for yourself btw)

**Comment by alecxvs** [comment]
I'm at work right now so I can't check it out right now

**Comment by misterff1** [comment]
![image2](https://cloud.githubusercontent.com/assets/3277023/7941005/a8da9264-0954-11e5-8ba4-a6604e2b86b9.png)

**Comment by alecxvs** [comment]
This happens when players try to chat? Does this error occur when plugins try to print to chat? If so, I'd like to see how that is getting called (eg is it calling Chat.Broadcast(...)?)

**Comment by alecxvs** [comment]
Also could you post your autorun integrator?

**Comment by misterff1** [comment]
Players simply can't chat at all. I can't even change the state of the chat. as far as I know it works for normal chat, chat:send, chat:print, etc etc.

**Comment by misterff1** [comment]
Here's the autorun integrator I use so far (I prefer this over one in each script, it's more stable. If you could make this one solve the chat:send issue I would use it instead of the one used by installing):

http://pastebin.com/gA9hCk8M

**Comment by alecxvs** [comment]
I think the problem is that I've been setting Chat.Send instead of Chat:Send in the integration, I'll confirm which one actually works without UTChat later. Worst case, if both are valid, I change integration to handle both cases.

**Comment by alecxvs** [comment]
I'm committing a change to the integration, see if that fixes it.

**Comment by misterff1** [comment]
I'll give this a go today. Will let you know about the results

**Comment by misterff1** [comment]
works like a charm now. Would love to keep using my own autorun integrator if possible though to avoid having to install the integrator all the time and currently that one throws errors. Could you see what's going wrong in it? It used to work without any issues.
![image3](https://cloud.githubusercontent.com/assets/3277023/7958654/96e9fbd8-09f1-11e5-8344-94335b580e5e.png)

**Comment by alecxvs** [comment]
This only happens with your integration installed?

It doesn't seem to be related, the errors refer to applying a format that doesn't exist, which I didn't think was possible to do from integration (even though you can tell from the call stack it probably originated from integration there). I would expect the problem to be a bug in a chat handler or the color or fade format got overwritten or deleted.

**Comment by misterff1** [comment]
It seems to be a one time thing for those who are online when all scripts are being reloaded, doesn't break anything apparently. So I guess this one is fixed then :)
