### ISSUE TITLE
Error in ModuleUnload

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#25]
![image7](https://cloud.githubusercontent.com/assets/3277023/7971141/fd7a0ef0-0a42-11e5-93ff-c226958303ac.png)
Happens when joining the server sometimes. No idea how it happens or why, but it does.
(sorry for the issue spam btw :P)

**Comment by alecxvs** [comment]
That error is in the module 'skiing' and is not in an integration file. Unless the code it refers to is a utchat or utext method, this issue is unrelated.

**Comment by misterff1** [comment]
Closing, my bad.
